spring.application.name=studentcrud
# Application Configuration - Student CRUD Portal
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Port
server.port=8081